# Generated by Django 3.2.8 on 2021-10-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img_str',
        ),
    ]
