# Generated by Django 3.2.8 on 2021-10-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0002_remove_image_img_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='keywords',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
