# Generated by Django 3.2.8 on 2021-10-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0003_auto_20211018_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='album',
            field=models.ManyToManyField(related_name='album', to='img.Albums'),
        ),
    ]
