# Generated by Django 3.2.8 on 2021-10-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0004_auto_20211018_0644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Albums',
            new_name='Album',
        ),
    ]
