# Generated by Django 3.2.8 on 2021-10-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0005_rename_albums_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.ManyToManyField(related_name='images', to='img.Album'),
        ),
    ]
