# Generated by Django 3.2.8 on 2021-10-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0006_alter_image_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='keywords',
        ),
        migrations.AddField(
            model_name='image',
            name='keywords',
            field=models.ManyToManyField(related_name='keyword', to='img.Keyword'),
        ),
    ]
