# Generated by Django 3.2.8 on 2021-10-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0007_auto_20211018_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='keywords',
            field=models.ManyToManyField(related_name='keywords', to='img.Keyword'),
        ),
    ]
